### ISSUE TITLE
LWT Implementation

### ISSUE THREAD

**Issue by Anto79-ops** [Olen/solar-monitor#14]
hi, just curious would it possible to incorporate the Last Will and Testament (LWT) protocol for this project?

https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/

would be used to send disconnect/error notifcations to the user

**Comment by Olen** [comment]
Could be a nice feature.  I have not looked at t in detal, but it seems to be easy enough to add to the datalogger.py.
Please send a PR

**Comment by Olen** [comment]
Paho-example.
Need to figure out exactly what we want to set as the LWT

https://mntolia.com/mqtt-last-will-testament-explained-with-examples/
