### ISSUE TITLE
Heater on (for heated batteries) support

### ISSUE THREAD

**Issue by Anto79-ops** [Olen/solar-monitor#16]
Renogy just added support for "Battery Heating Mode" in the DC Home App version Android 1.10.5 (and also the Apple version)

Shows up here:

![a48eaba1-51f6-4818-b625-4364e81c0851_16523780959363](https://user-images.githubusercontent.com/79593761/168618253-c3ebef11-69dc-4075-aa38-88c978044265.png)

Would be great if this status can also be added to script. thanks again for the efforts here.

**Comment by Olen** [comment]
You need to find the correct IDs to poll, or find out how to read the values from already received data.
Look at e.g. #7 to help reading the raw bluetooth-data

**Comment by Anto79-ops** [comment]
thanks, I'll give this a try. Just to confirm, I don't really need anything special for this, just an app on my android phone?

**Comment by Olen** [comment]
Just some spring cleaning of old issues.

I guess you have more info now on how to get the data you need.
