### ISSUE TITLE
Adding a license (GPL v 3.0)

### ISSUE THREAD

**Issue by Olen** [Olen/solar-monitor#9]
Since this project has started gathering at least a few contributors, and some interesst from other 3.parties, I want to add a LICENSE to the code.
For me, GPL-v3 is my preferred choice, but I can not add that license if some of the other contributors reject it (then we would first need to remove your code).

So please to the following contributors:
@oedo808 
@henrik242 
@tokfrans03 

Add a simple "Yes" or similar comment here, and I will add the necessary files and changes for GPL v3.0 to be applied.

**Comment by henrik242** [comment]
GPL-v3 is fine with me!

**Comment by oedo808** [comment]
Works for me, thanks!

**Comment by tokfrans03** [comment]
Fine by me!

Sent from a small piece of glass

> 14 mars 2022 kl. 13:50 skrev oedo808 ***@***.***>:
> 
> ﻿
> Works for me, thanks!
>

**Comment by Olen** [comment]
Great. Thanks for our quick responses.
Adding GPL-v3 license.txt
